spring:
  main:
    banner-mode: off
  liquibase:
    change-log: liquibase.yml
    default-schema: public
    liquibase-schema: public
  r2dbc:
    pool:
      initial-size: 5
      max-size: 10
app:
  loop:
    interval: 10s
    reachable-timeout: 10s
