spring:
  main:
    banner-mode: off
  liquibase:
    change-log: liquibase.yml
    default-schema: public
    liquibase-schema: public
  r2dbc:
    pool:
      initial-size: 5
      max-size: 10
app:
  loop:
    interval: 10s
    reachable-timeout: 10s
    tries: 3
    update-last-events: 0
  network-stability:
    interval: 2s
    timeout: 1s
    tries: 3
    wait-for-stable-network-timeout: 10m
    consecutive-tries-to-consider-online: 20
    hosts:
      - 188.190.254.254
      - 1.1.1.1
      - 8.8.8.8
