spring:
  r2dbc:
    url: r2dbc:h2:file:///./testdb
    username: test
    password: test
  liquibase:
    url: jdbc:h2:file:./testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;CASE_INSENSITIVE_IDENTIFIERS=TRUE;AUTO_SERVER=true;AUTO_SERVER_PORT=9090
    user: test
    password: test
    driver-class-name: org.h2.Driver
    default-schema: public

logging:
  level:
    liquibase: INFO
    io.r2dbc.h2: DEBUG
