spring:
  main:
    banner-mode: off
  liquibase:
    change-log: liquibase.yml
    default-schema: public
    liquibase-schema: public
  datasource:
    driver-class-name: org.postgresql.Driver
app:
  loop:
    interval: 10s
    reachable-timeout: 10s
