spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    driver-class-name: org.postgresql.Driver
    default-schema: public
app:
  loop:
    interval: 5s
    reachable-timeout: 5s
    tries: 2
  network-stability:
    tries: 2
    consecutive-tries-to-consider-online: 5
